Support for loading data from csv files
BBMRI-cz/fhir-module pull request #12
Opened 2024-01-09 14:40 UTC by SimonKonar

## Negotiator pull request:

### Description:

Added support for reading data from Csv files in persistence. The goal is to have more supported formats to extract data from. 

### Checklist:

_Make sure you tick all the boxes bellow if they are true or do not apply:_

- [ +] I have performed a self-review of my code
- [ +] My code follows [Google Python Style](https://google.github.io/styleguide/pyguide.html)
- [ +] I have made my code as simple as possible
- [ +] I have added unit tests and the code coverage has not decreased
- [ +] I have updated the documentation in all relevant places

2024-01-18 16:02 UTC, RadovanTomik requested changes
Please address comments and update the documentation.

2024-01-18 16:02 UTC, RadovanTomik commented on service/blaze_service.py
> +        # self._patient_service = patient_service
remove commented code

2024-01-19 10:14 UTC, SimonKonar commented on Dockerfile
> +FROM python:3.12-alpine
Version is changed back to 3.11

2024-01-19 10:18 UTC, SimonKonar commented on Dockerfile
> +FROM python:3.12-alpine
version reverted back to 3.11

2024-01-19 10:36 UTC, SimonKonar commented on main.py
> +        blaze_service = BlazeService(repository_factory=repository_factory, blaze_url=BLAZE_URL)
Blaze no longer uses factory as a parameter.

2024-01-19 10:38 UTC, SimonKonar commented on main.py
> +        repository_factory = get_repository_factory()
I created function in which RECORDS_FILE_TYPE is checked, and corresponding factory is instantiated, or Exception is thrown. I wanted to do it like this, so main.py is clearer, and when new file types will be added, only this function will change.

2024-01-19 10:39 UTC, SimonKonar commented on persistence/csv_util.py
> +class WrongSampleMapException(Exception):
moved to separate file, also throwing this exception comes with error message as well

2024-01-19 10:39 UTC, SimonKonar commented on persistence/factories/factory_util.py
> +class WrongRecordsFileTypeException(Exception):
moved to separate file, also throwing this exception comes with error message as well

2024-01-19 10:39 UTC, SimonKonar commented on service/blaze_service.py
> +        # self._patient_service = patient_service
comments removed

2024-01-23 21:13 UTC, merged